name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: üë©‚Äçüî¨ Test
    runs-on: ['self-hosted', 'kubernetes']
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: pytest
        run: pytest --doctest-modules --junitxml=junit/test-results.xml --cov=. --cov-report=xml
        
      - uses: docker/metadata-action@v3
        id: metadata
        with:
          images: docker.io/mlphilli/literate-spork
        
      - uses: docker/login-action@v1
        with:
          registry: docker.io
          username: mlphilli
          password: ${{ secrets.docker_secret }}
        
      - name: kaniko-action
        uses: int128/kaniko-action@v1
        with:
          push: false
          kaniko-args: "--tarPath=image.tar"
          #tags: mitchell
          #cache: true
          #cache-repository: docker.io/mlphilli/cache
          
      
#       - name: Kaniko builder
#         uses: aevea/action-kaniko@v0.9.0
#         with:
#           username: mlphilli
#           password: ${{ secrets.docker_secret }}
#           image: mlphilli/literate-spork
#           cache: true
#           cache_registry: mlphilli/cache
#           debug: true
#           skip_unchanged_digest: true
#           extra_args: "--skip-tls-verify"
